# Exercise 2: NLP and feature engineering
----

In this exercise, we will use a synthetic dataset: data created by AI for illustration purposes, you may additionally also try using your own data.

Today, we will use this data for analysis and feature extraction using NLP, focusing on pre-processing steps. 

While these operations are tailored to Bag of Words approaches, they help illustrate the complications a computer faces when dealing with text.

In [1]:
#PACKAGES -
#NOTE: you should import all packages you need here, but for now, we will do this in-line.
import pandas as pd

### 1. Read in the data

In [2]:
sentences = ["I'm going to the bank.", "I'm going to the bank.", "I'm going to the bank.", "I need to visit the bank today.", "I'm heading to the bank to withdraw some cash.", "The bank is where I'm off to.", "I have an appointment at the bank.", "Let's spend the day by the river bank.", "The river bank is a peaceful place to relax.", "I enjoy walking along the river bank.", "We can have a picnic by the river bank.",
"She has a cool job.", "She has a cool job.", "She has a cool job.", "Her job is really interesting and fun.", "She works in a creative field and loves it.", "That job of hers is so unique.", "She's lucky to have such a cool profession.", "Her workplace is always chilly.", "She works in a refrigerated environment.", "The temperature in her office is freezing.", "She needs to bundle up for her job.",
"You need to check the trunk.", "You need to check the trunk.", "You need to check the trunk.", "Don't forget to look in the trunk of the car.", "There might be something important in the trunk.", "Make sure to verify the contents of the trunk.", "The trunk needs to be inspected for any damage.", "Take a look at the tree trunk for any damage.", "The trunk of the old tree might have some interesting carvings.", "Check if the tree trunk needs to be treated for pests.", "See if there are any unique patterns or textures on the tree trunk.",
"I saw her duck.", "I saw her duck.", "I saw her duck.", "Her duck was waddling in the park.", "The duck she owns is so cute.", "I spotted her duck by the pond.", "Her duck was quacking loudly.", "She ducked to avoid the flying object.", "Her quick ducking saved her from the falling branch.", "I noticed her sudden ducking movement.", "She ducked and dodged the incoming ball.",
"She has a great figure.", "She has a great figure.", "She has a great figure.", "Her body shape is very flattering.", "She carries herself with grace and confidence.", "Her figure is well-proportioned and attractive.", "She knows how to dress to highlight her figure.", "The numerical figure she presented was impressive.", "Her calculations yielded a significant figure.", "The data supports a substantial figure.", "The figure she quoted was accurate and reliable."]

context = ["bank", "bank-money", "bank-river", "bank-money", "bank-money", "bank-money", "bank-money", "bank-river", "bank-river", "bank-river", "bank-river", "cool", "cool-nice", "cool-cold", "cool-nice", "cool-nice", "cool-nice", "cool-nice", "cool-cold", "cool-cold", "cool-cold", "cool-cold", "trunk", "trunk-car", "trunk-tree", "trunk-car", "trunk-car", "trunk-car", "trunk-car", "trunk-tree", "trunk-tree", "trunk-tree", "trunk-tree", 
           "duck", "duck-animal", "duck-down", "duck-animal", "duck-animal", "duck-animal", "duck-animal", "duck-down", "duck-down", "duck-down", "duck-down", "figure", "figure-body", "figure-number", "figure-body", "figure-body", "figure-body", "figure-body", "figure-number", "figure-number", "figure-number", "figure-number"]

set = ["bank-base", "bank-base-money", "bank-base-river", "bank-money", "bank-money", "bank-money", "bank-money", "bank-river", "bank-river", "bank-river", "bank-river", "cool-base", "cool-base-nice", "cool-base-cold", "cool-nice", "cool-nice", "cool-nice", "cool-nice", "cool-cold", "cool-cold", "cool-cold", "cool-cold", "trunk-base", "trunk-base-car", "trunk-base-tree", "trunk-car", "trunk-car", "trunk-car", "trunk-car", "trunk-tree", "trunk-tree", "trunk-tree", "trunk-tree", 
           "duck-base", "duck-base-animal", "duck-base-down", "duck-animal", "duck-animal", "duck-animal", "duck-animal", "duck-down", "duck-down", "duck-down", "duck-down", "figure-base", "figure-base-body", "figure-base-number", "figure-body", "figure-body", "figure-body", "figure-body", "figure-number", "figure-number", "figure-number", "figure-number"]

contextdf = pd.DataFrame({'Sentence': sentences, 'Context': context, 'Set': set})

We will use two subsets of this dataset: 
1. Sentences referring to *figure* (body vs. number)
2. Sentences referring to *trunk* (car vs. treer)

In [3]:
figure_df = contextdf[contextdf['Set'].isin(['figure-body', 'figure-number'])].reset_index(drop=True).copy()
figure_df

,Sentence,Context,Set
0,Her body shape is very flattering.,figure-body,figure-body
1,She carries herself with grace and confidence.,figure-body,figure-body
2,Her figure is well-proportioned and attractive.,figure-body,figure-body
3,She knows how to dress to highlight her figure.,figure-body,figure-body
4,The numerical figure she presented was impress...,figure-number,figure-number
5,Her calculations yielded a significant figure.,figure-number,figure-number
6,The data supports a substantial figure.,figure-number,figure-number
7,The figure she quoted was accurate and reliable.,figure-number,figure-number

In [4]:
trunk_df = contextdf[contextdf['Set'].isin(['trunk-car', 'trunk-tree'])].reset_index(drop=True).copy()
trunk_df

                                            Sentence     Context         Set
0      Don't forget to look in the trunk of the car.   trunk-car   trunk-car
1   There might be something important in the trunk.   trunk-car   trunk-car
2     Make sure to verify the contents of the trunk.   trunk-car   trunk-car
3    The trunk needs to be inspected for any damage.   trunk-car   trunk-car
4      Take a look at the tree trunk for any damage.  trunk-tree  trunk-tree
5  The trunk of the old tree might have some inte...  trunk-tree  trunk-tree
6  Check if the tree trunk needs to be treated fo...  trunk-tree  trunk-tree
7  See if there are any unique patterns or textur...  trunk-tree  trunk-tree

### sample the data (for testing)

### 2. Examples of Pre-processing Steps - 


a.  lowercasing  
b.  tokenization  
c.  stopword removal  
d.  stemming and/or lemmatizing  
e.  cleaning: removing punctuation, line breaks, double spaces

#### Lowercasing:

In [5]:
#pre-check:
print("Sample text before lowercasing:")
print(figure_df['Sentence'][:1])

#lowercase all the articles:
sentences_lower_cased = [art.lower() for art in figure_df['Sentence']]

#post-check:
print("Sample text after lowercasing:")
print(sentences_lower_cased[:1])

Sample text before lowercasing:
0    Her body shape is very flattering.
Name: Sentence, dtype: str
Sample text after lowercasing:
['her body shape is very flattering.']

#### Tokenization:

In [6]:
#TOKENIZATION, SIMPLE - 

#pre-check:
print("Sample text before tokenization:")
print(figure_df['Sentence'][:1])

#basic solution, using the string method `.split()`. 
sentences_tokenized = [art.split() for art in figure_df['Sentence']]

#post-check:
print("Sample text after tokenization:")
print(sentences_tokenized[:1])

Sample text before tokenization:
0    Her body shape is very flattering.
Name: Sentence, dtype: str
Sample text after tokenization:
[['Her', 'body', 'shape', 'is', 'very', 'flattering.']]

In [7]:
#TOKENIZATION, ADVANCED -

#more sophisticated solution, using the NLTK library.
#NOTE: TbWT separtes punctuation (world!), handles contractions (can't), and splits critics (it's).
from nltk.tokenize import TreebankWordTokenizer #for tokenization

#pre-check:
print("Sample text before advanced tokenization:")
print(trunk_df['Sentence'][:1])

#tokenize the articles:
sentences_tokenized = [TreebankWordTokenizer().tokenize(art) for art in trunk_df['Sentence']]

#post-check:
print("Sample text after advanced tokenization:")
print(sentences_tokenized[:1])

Sample text before advanced tokenization:
0    Don't forget to look in the trunk of the car.
Name: Sentence, dtype: str
Sample text after advanced tokenization:
[['Do', "n't", 'forget', 'to', 'look', 'in', 'the', 'trunk', 'of', 'the', 'car', '.']]

In [8]:
#cut cell

#TOKENIZATION, MORE ADVANCED -
import regex #for regular expressions
import nltk #for natural language processing 

#create your own tokenizer that first split into sentences. In this way,`TreebankWordTokenizer` works better - 

#nltk.download("punkt_tab") #uncomment this if needed.

#let's define a class for our (custom) tokenizer:
#NOTE: what does 'self' mean in this context? 
class MyTokenizer:
    def tokenize(self, text): #it takes a string as input.
        tokenizer = TreebankWordTokenizer() #initialize the tokenizer
        result = [] #initialize the result list
        word = r"\p{letter}" #this is a regex pattern for letters
        for sent in nltk.sent_tokenize(text): #split the text into sentences
            tokens = tokenizer.tokenize(sent)   #tokenize the sentence (with TbWT) 
            tokens = [t for t in tokens if regex.search(word, t)] #NOTE: what is this doing?
            result += tokens #add the (valid) tokens to the result list
        return result #return the result list

#instantiate the tokenizer:
mytokenizer = MyTokenizer()

#pre-check:
print("Sample text before our custom tokenization:")
print(figure_df['Sentence'][:1])

#run the tokenizer on our articles: 
articles_tokenized = [mytokenizer.tokenize(art) for art in figure_df['Sentence']]

#post-check:
print("Sample text after our custom tokenization:")
print(articles_tokenized[:1])

Sample text before our custom tokenization:
0    Her body shape is very flattering.
Name: Sentence, dtype: str
Sample text after our custom tokenization:
[['Her', 'body', 'shape', 'is', 'very', 'flattering']]

#### Stopwords:

In [9]:
#STOPWORDS, SIMPLE - 

#let's use NLTK to get a list of stopwords:
from nltk.corpus import stopwords
#nltk.download("stopwords") #NOTE: uncomment this if needed. 

#let's create a list of stopwords:
mystopwords = stopwords.words("english")
mystopwords.extend(["add", "more", "words"]) # it's just a list, so we can add more words if we want to.

print(mystopwords) #just to demonstrate the point...

['a', 'about', 'above', 'after', 'again', 'against', 'ain', 'all', 'am', 'an', 'and', 'any', 'are', 'aren', "aren't", 'as', 'at', 'be', 'because', 'been', 'before', 'being', 'below', 'between', 'both', 'but', 'by', 'can', 'couldn', "couldn't", 'd', 'did', 'didn', "didn't", 'do', 'does', 'doesn', "doesn't", 'doing', 'don', "don't", 'down', 'during', 'each', 'few', 'for', 'from', 'further', 'had', 'hadn', "hadn't", 'has', 'hasn', "hasn't", 'have', 'haven', "haven't", 'having', 'he', "he'd", "he'll", 'her', 'here', 'hers', 'herself', "he's", 'him', 'himself', 'his', 'how', 'i', "i'd", 'if', "i'll", "i'm", 'in', 'into', 'is', 'isn', "isn't", 'it', "it'd", "it'll", "it's", 'its', 'itself', "i've", 'just', 'll', 'm', 'ma', 'me', 'mightn', "mightn't", 'more', 'most', 'mustn', "mustn't", 'my', 'myself', 'needn', "needn't", 'no', 'nor', 'not', 'now', 'o', 'of', 'off', 'on', 'once', 'only', 'or', 'other', 'our', 'ours', 'ourselves', 'out', 'over', 'own', 're', 's', 'same', 'shan', "shan't", 'she', "she'd", "she'll", "she's", 'should', 'shouldn', "shouldn't", "should've", 'so', 'some', 'such', 't', 'than', 'that', "that'll", 'the', 'their', 'theirs', 'them', 'themselves', 'then', 'there', 'these', 'they', "they'd", "they'll", "they're", "they've", 'this', 'those', 'through', 'to', 'too', 'under', 'until', 'up', 've', 'very', 'was', 'wasn', "wasn't", 'we', "we'd", "we'll", "we're", 'were', 'weren', "weren't", "we've", 'what', 'when', 'where', 'which', 'while', 'who', 'whom', 'why', 'will', 'with', 'won', "won't", 'wouldn', "wouldn't", 'y', 'you', "you'd", "you'll", 'your', "you're", 'yours', 'yourself', 'yourselves', "you've", 'add', 'more', 'words']

In [10]:
# now, remove stopwords from the corpus:

#pre-check:
print("Sample text before removing stopwords:")
print(figure_df['Sentence'][:1])

#stopword removal:
sentences_without_stopwords = [] #initialize an empty list
for sentence in figure_df['Sentence']: #for each sentence
    sentence_no_stop = "" #initialize an empty string
    for word in sentence.lower().split(): #for each word in the list of lowered words from the sentence
        if word not in mystopwords: #if the word is not a stopword
            sentence_no_stop = sentence_no_stop + " " + word #add the word to the empty string
    sentences_without_stopwords.append(sentence_no_stop) #add the sentence sans stopwords to the list

#post-check:
print("Sample text after removing stopwords:")
print(sentences_without_stopwords[:2])

Sample text before removing stopwords:
0    Her body shape is very flattering.
Name: Sentence, dtype: str
Sample text after removing stopwords:
[' body shape flattering.', ' carries grace confidence.']

In [11]:
# same solution, but with list comprehension:
# NOTE: can you explain how this works? 
sentences_without_stopwords = [" ".join([w for w in sentence.lower().split() if w not in mystopwords]) for sentence in figure_df['Sentence']]
print(sentences_without_stopwords[:1])

['body shape flattering.']

#### Stemming and lemmatization:

In [12]:
#STEMMING AND LEMMATIZATION -

from nltk.stem.snowball import SnowballStemmer #this stems by removing suffixes (e.g. -ing, -ed)

stemmer = SnowballStemmer("english") #initialize the stemmer

#pre-check:
print("Sample text before stemming:")
print(figure_df['Sentence'][:1])

stemmed_text = [] #initialize an empty list
for sentence in figure_df['Sentence']: #for each sentence
    stemmed_words = "" #initialize an empty string
    for word in sentence.lower().split(): #for each word in the list of lowered words from the sentence
        stemmed_words = stemmed_words + " " + stemmer.stem(word) #stem the word and add it to the empty string
    stemmed_text.append(stemmed_words.strip()) #add the stemmed sentence to the list

#post-check:
print("Sample text after stemming:")
print(stemmed_text[:2])

Sample text before stemming:
0    Her body shape is very flattering.
Name: Sentence, dtype: str
Sample text after stemming:
['her bodi shape is veri flattering.', 'she carri herself with grace and confidence.']

In [13]:
# compare tokeninzation and lemmatization using `Spacy`:

import spacy 
#spacy.cli.download("en_core_web_sm") #uncomment this if needed.
nlp = spacy.load("en_core_web_sm") #load the small english model.

#pre-check:
print("Sample text before lemmatization:")
print(figure_df['Sentence'][:1])

#let's lemmatize the articles:
lemmatized_sentences = [[token.lemma_ for token in nlp(art)] for art in figure_df['Sentence']]

#post-check:
print("Sample text after lemmatization:")
print(lemmatized_sentences[:1])

Sample text before lemmatization:
0    Her body shape is very flattering.
Name: Sentence, dtype: str
Sample text after lemmatization:
[['her', 'body', 'shape', 'be', 'very', 'flattering', '.']]

#### Cleaning:

In [ ]:
#### CLEANING: removing punctuation, line breaks, double spaces
import random

n = random.randint(0, len(figure_df) - 1)
figure_df['Sentence'].iloc[n] # print a random article to inspect.

## Typical cleaning up steps:
from string import punctuation
figure_df['Sentence'] = [art.replace('\n\n', '') for art in figure_df['Sentence']] # remove line breaks
figure_df['Sentence'] = ["".join([w for w in art if w not in punctuation]) for art in figure_df['Sentence']] # remove punctuation
figure_df['Sentence'] = [" ".join(art.split()) for art in figure_df['Sentence']] # remove double spaces by splitting the strings into words and joining these words again
figure_df['Sentence'].iloc[n] # print the same article to see whether the changes are in line with what you want

#### N-grams:

- Think about what type of n-grams you want to add to your feature set. Extract and inspect n-grams and/or collocations, and add them to your feature set if you think this is relevant.

In [ ]:
articles_bigrams = [["_".join(tup) for tup in nltk.ngrams(art.split(),2)] for art in figure_df['Sentence']] # creates bigrams
articles_bigrams[7][:5] # inspect the results...

# maybe we want both unigrams and bigrams in the feature set?
assert len(figure_df['Sentence'])==len(articles_bigrams)

articles_uniandbigrams = []
for a,b in zip([art.split() for art in figure_df['Sentence']],articles_bigrams):
    articles_uniandbigrams.append(a + b)

#and let's inspect the outcomes again.
articles_uniandbigrams[7]
len(articles_uniandbigrams[7]),len(articles_bigrams[7]),len(figure_df['Sentence'].iloc[7].split())


#Or, if you want to inspect collocations:
text = [nltk.Text(tkn for tkn in art.split()) for art in figure_df['Sentence'] ]
text[7].collocations(num=10)

### 3. Extract entities and other meaningful information (enrich your feature set)

Depending on your interests and the nature of the data, you could:

- use regular expressions to distinguish relevant from irrelevant texts, or to extract substrings
- use NLP techniques such as Named Entity Recognition to extract entities that occur.

#### pos-tagging:

In [ ]:
#tokenize and POS-tag with NLTK:
tokens = [nltk.word_tokenize(sentence) for sentence in figure_df['Sentence']]
tagged = [nltk.pos_tag(sentence) for sentence in tokens]
print(tagged[0]) # inspect the first article's POS tags

#### entity detection:

In [ ]:
#detect named entities with Spacy:
nlp = spacy.load('en_core_web_sm')

#let's get the named entities:
doc = [nlp(sentence) for sentence in figure_df['Sentence']]
for i in doc:
    for ent in i.ents:
        if ent.label_ == 'PERSON':
            print(ent.text, ent.label_ )

### 4. Create your own pre-processing and feature extraction pipeline:

Combine the methods above to produce a list of preprocessed texts (features) for your classification model.

In [ ]:
#spacy download:
from spacy.cli import download

#download dutch model:
download("nl_core_news_sm") #uncomment this if needed.

In [ ]:
#spacy download:
from spacy.cli import download

#download dutch model:
download("nl_core_news_sm") #uncomment this if needed.


import re #for regular expressions
import nltk #for nlp (here: tokenization)
from nltk.corpus import stopwords #for stopwords
from nltk.stem import WordNetLemmatizer #for lemmatization

def preprocess_text(texts, custom_stopwords=None):
    #NOTE: better lemmatizer that uses the WordNet lexical database.
    #NOTE: you can even pass it POS tags to improve the lemmatization (not done here).
    lemmatizer = WordNetLemmatizer() 
    #get the default stopwords from NLTK (en).
    stop_words = set(stopwords.words('english'))
    
    #add custom stopwords if provided
    if custom_stopwords:
        stop_words.update(custom_stopwords)
    
    #instantiate an empty list for processed texts
    processed_texts = []

    #interate over the texts
    for text in texts:
        try:
            #lowercase
            text = text.lower()

            #tokenize with NLTK tokenizer
            tokens = nltk.word_tokenize(text)
            
            #remove non-alphabetic characters from tokens
            tokens = [re.sub(r'[^a-z\s]', '', token) for token in tokens]
            
            #combined stopwords removal and lemmatization
            tokens = [lemmatizer.lemmatize(word) for word in tokens if word not in stop_words]
            
            #join tokens back to string=
            processed_text = ' '.join(tokens)

            #remove any double spaces that remain:
            processed_text = re.sub(r'\s+', ' ', processed_text).strip()
            
            #append processed text to output list:
            processed_texts.append(processed_text)
        
        except Exception as e: #raise error if smth goes wrong: 
            print(f"Error processing text: {text}. Error: {e}")
            processed_texts.append("")
    
    return processed_texts

In [ ]:
#execute the function:
processed_articles = preprocess_text(figure_df['Sentence'])

### 5. Train a supervised classifier

Use your code from yesterday's assignment to train a classifier. 

Perform the same classification task, but this time carefully consider which feature set you want to use.

Reflect on the options listed above, and extract features that you think are relevant to include. 

Carefully consider **pre-processing steps**: what type of features will you feed your algorithm? Do you, for example, want to manually remove stopwords, or include ngrams? 

Use these features as input for your classifier, and investigate the effects hereof on performance of the classifier. 

Not that the purpose is not to build the perfect classifier, but to inspect the effects of different feature engineering decisions on the outcomes of your classification algorithm.

In [ ]:
# let's split the data:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(processed_articles, figure_df['Set'], test_size=0.2)    # 80% training and 20% testing

#let's vectorize the data:
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
myvectorizer= CountVectorizer(stop_words=None) # you can further modify this yourself.
#myvectorizer= TfidfVectorizer(stop_words=None) # you can further modify this yourself.

#Fit the vectorizer, and transform.
X_features_train = myvectorizer.fit_transform(X_train)
X_features_test = myvectorizer.transform(X_test)

#let's train a model:
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report

model = MultinomialNB()
model.fit(X_features_train, y_train)
y_pred = model.predict(X_features_test)

print(f"Accuracy : {accuracy_score(y_test, y_pred)}")
print(classification_report(y_test, y_pred))